# Generated by Django 4.2.28 on 2026-02-13 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_date', models.DateField(verbose_name='Date de relance')),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('sms', 'SMS'), ('letter', 'Courrier')], max_length=20, verbose_name='Type de relance')),
                ('message', models.TextField(verbose_name='Message')),
                ('customer_response', models.TextField(blank=True, verbose_name='Réponse du client')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Date de suivi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='sales.invoice', verbose_name='Facture')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relance de paiement',
                'verbose_name_plural': 'Relances de paiement',
                'ordering': ['-reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant total (DA)')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Acompte (DA)')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant restant (DA)')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name="Nombre d'échéances")),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant par échéance (DA)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('defaulted', 'En défaut'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='sales.invoice', verbose_name='Facture')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de paiement',
                'verbose_name_plural': 'Plans de paiement',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de paiement')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (DA)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement Bancaire'), ('check', 'Chèque'), ('card', 'Carte Bancaire'), ('other', 'Autre')], max_length=20, verbose_name='Mode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire/chèque')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='Confirmé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.invoice', verbose_name='Facture')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField(verbose_name="Numéro d'échéance")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (DA)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé (DA)')),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde dû (DA)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('overdue', 'En retard'), ('partial', 'Partiellement payé')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.paymentplan', verbose_name='Plan de paiement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Échéance',
                'verbose_name_plural': 'Échéances',
                'ordering': ['due_date', 'installment_number'],
                'unique_together': {('payment_plan', 'installment_number')},
            },
        ),
    ]
