# Generated by Django 4.2.28 on 2026-03-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement Bancaire'), ('check', 'Chèque'), ('card', 'Carte Bancaire'), ('installment', 'Versement échelonné'), ('other', 'Autre')], max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
