# Generated by Django 4.2.28 on 2026-02-13 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField(verbose_name="Date d'achat")),
                ('purchase_price_fob', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix FOB')),
                ('exchange_rate_to_da', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de change vers DA')),
                ('purchase_price_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Prix d'achat en DA")),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='FreightCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freight_method', models.CharField(choices=[('sea', 'Maritime'), ('air', 'Aérien')], max_length=10, verbose_name='Mode de transport')),
                ('freight_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût de fret')),
                ('freight_exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de change du fret')),
                ('insurance_cost_da', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Coût d'assurance (DA)")),
                ('other_logistics_costs_da', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Autres frais logistiques (DA)')),
                ('total_freight_cost_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total des frais de transport (DA)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('freight_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freight_costs', to='core.currency', verbose_name='Devise du fret')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freight_cost', to='purchases.purchase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coût de transport',
                'verbose_name_plural': 'Coûts de transport',
            },
        ),
        migrations.CreateModel(
            name='CustomsDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration_date', models.DateField(verbose_name='Date de déclaration')),
                ('declaration_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de déclaration')),
                ('cif_value_da', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur CIF (DA)')),
                ('customs_tariff_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux tarifaire douanier (%)')),
                ('import_duty_da', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Droit d'importation (DA)")),
                ('tva_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux TVA (%)')),
                ('tva_amount_da', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant TVA (DA)')),
                ('other_fees_da', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Autres frais douaniers (DA)')),
                ('total_customs_cost_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total des frais douaniers (DA)')),
                ('is_cleared', models.BooleanField(default=False, verbose_name='Dédouané')),
                ('clearance_date', models.DateField(blank=True, null=True, verbose_name='Date de dédouanement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customs_declaration', to='purchases.purchase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déclaration douanière',
                'verbose_name_plural': 'Déclarations douanières',
                'ordering': ['-declaration_date'],
            },
        ),
    ]
