# Generated by Django 4.2.28 on 2026-03-29 11:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Achat (Conteneur)', 'verbose_name_plural': 'Achats (Conteneurs)'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price_da',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price_fob',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate_to_da',
            field=models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Taux de change vers DA'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='PurchaseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField(verbose_name='N° de ligne')),
                ('make', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('engine_type', models.CharField(blank=True, max_length=100, verbose_name='Type de moteur')),
                ('vin_chassis', models.CharField(blank=True, help_text='Optionnel à la commande — à renseigner à la réception du véhicule.', max_length=50, verbose_name='VIN / Châssis')),
                ('fob_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix FOB (devise)')),
                ('fob_price_da', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Prix FOB (DA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchases.purchase', verbose_name='Achat (conteneur)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Article d'achat",
                'verbose_name_plural': "Articles d'achat",
                'ordering': ['purchase', 'line_number'],
                'unique_together': {('purchase', 'line_number')},
            },
        ),
    ]
