# Generated by Django 4.2.28 on 2026-03-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_options_and_more'),
        ('inventory', '0002_remove_vehicle_vehicle_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='purchase_line_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='purchases.purchaselineitem', verbose_name="Article d'achat"),
        ),
    ]
