# Generated by Django 4.2.28 on 2026-02-13 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du rapport')),
                ('report_type', models.CharField(choices=[('profit_analysis', 'Analyse de Profit'), ('trader_performance', 'Performance des Traders'), ('inventory_status', 'État du Stock'), ('sales_summary', 'Résumé des Ventes'), ('payment_status', 'État des Paiements'), ('commission_report', 'Rapport de Commissions')], max_length=50, verbose_name='Type de rapport')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('filter_parameters', models.JSONField(default=dict, verbose_name='Paramètres de filtre')),
                ('is_public', models.BooleanField(default=False, verbose_name='Rapport public')),
                ('allowed_roles', models.JSONField(default=list, verbose_name='Rôles autorisés')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de rapport',
                'verbose_name_plural': 'Modèles de rapport',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la planification')),
                ('frequency', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('quarterly', 'Trimestriel')], max_length=20, verbose_name='Fréquence')),
                ('email_subject', models.CharField(max_length=200, verbose_name="Sujet de l'email")),
                ('next_run', models.DateTimeField(verbose_name='Prochaine exécution')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause'), ('disabled', 'Désactivé')], default='active', max_length=20, verbose_name='Statut')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Destinataires')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reports.reporttemplate', verbose_name='Modèle de rapport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport planifié',
                'verbose_name_plural': 'Rapports planifiés',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='running', max_length=20, verbose_name='Statut')),
                ('record_count', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'enregistrements")),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin du fichier')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Exécuté par')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.reporttemplate', verbose_name='Modèle de rapport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exécution de rapport',
                'verbose_name_plural': 'Exécutions de rapport',
                'ordering': ['-start_time'],
            },
        ),
    ]
