# Generated by Django 4.2.28 on 2026-03-29 14:18

import customers.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_document',
            field=models.FileField(blank=True, help_text='PDF, JPG ou PNG — max 10 Mo (optionnel)', null=True, upload_to='customers/passports/', validators=[customers.models.validate_passport_file], verbose_name="Passeport / Pièce d'identité"),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customers/photos/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format : +213XXXXXXXXX ou 0XXXXXXXXX', regex='^(\\+213|0)[1-9][0-9]{8}$')], verbose_name='Téléphone'),
        ),
    ]
