# Generated by Django 4.2.28 on 2026-02-13 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Période fermée')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_commission_periods', to=settings.AUTH_USER_MODEL, verbose_name='Fermée par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Période de commission',
                'verbose_name_plural': 'Périodes de commission',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nom du niveau')),
                ('min_sales_count', models.PositiveIntegerField(verbose_name='Nombre minimum de ventes')),
                ('max_sales_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre maximum de ventes')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de commission (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Niveau de commission',
                'verbose_name_plural': 'Niveaux de commission',
                'ordering': ['min_sales_count'],
            },
        ),
        migrations.CreateModel(
            name='CommissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes')),
                ('total_sales_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur totale des ventes (DA)')),
                ('total_margin', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Marge totale (DA)')),
                ('base_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission de base (DA)')),
                ('tier_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bonus de niveau (DA)')),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Commission totale (DA)')),
                ('payout_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de paiement')),
                ('payout_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('payout_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_summaries', to='commissions.commissionperiod', verbose_name='Période')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Trader')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résumé de commission',
                'verbose_name_plural': 'Résumés de commission',
                'ordering': ['-period__year', '-period__month', 'trader__first_name'],
                'unique_together': {('trader', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé (DA)')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Virement Bancaire'), ('cash', 'Espèces'), ('check', 'Chèque')], max_length=20, verbose_name='Mode de paiement')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence bancaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Payé par')),
                ('summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payment', to='commissions.commissionsummary', verbose_name='Résumé de commission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement de commission',
                'verbose_name_plural': 'Paiements de commission',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Bonus'), ('penalty', 'Pénalité'), ('correction', 'Correction'), ('special', 'Spécial')], max_length=20, verbose_name="Type d'ajustement")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (DA)')),
                ('reason', models.TextField(verbose_name='Raison')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_adjustments', to='commissions.commissionperiod', verbose_name='Période')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Trader')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajustement de commission',
                'verbose_name_plural': 'Ajustements de commission',
                'ordering': ['-created_at'],
            },
        ),
    ]
