# Generated by Django 4.2.28 on 2026-02-13 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=10, verbose_name='Thème')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية'), ('en', 'English')], default='fr', max_length=5, verbose_name='Langue')),
                ('dashboard_widgets', models.JSONField(default=list, verbose_name='Widgets du tableau de bord')),
                ('default_page_size', models.PositiveIntegerField(default=20, verbose_name="Nombre d'éléments par page")),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('browser_notifications', models.BooleanField(default=True, verbose_name='Notifications navigateur')),
                ('default_export_format', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('pdf', 'PDF')], default='excel', max_length=10, verbose_name="Format d'export par défaut")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
        migrations.CreateModel(
            name='TaxRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_type', models.CharField(choices=[('tva', 'TVA'), ('tariff', 'Tarif Douanier'), ('other', 'Autre')], max_length=20, verbose_name='Type de taxe')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux (%)')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'effet")),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique des taux de taxe',
                'verbose_name_plural': 'Historiques des taux de taxe',
                'ordering': ['-effective_date', 'tax_type'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=10, verbose_name='Niveau')),
                ('action_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('export', 'Export'), ('import', 'Import'), ('system', 'Système')], max_length=20, verbose_name="Type d'action")),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Journal système',
                'verbose_name_plural': 'Journaux système',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Bureau de Commerce Automobile Algérien', max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_nif', models.CharField(default='123456789012345', max_length=20, verbose_name="NIF de l'entreprise")),
                ('company_address', models.TextField(default='Alger, Algérie', verbose_name="Adresse de l'entreprise")),
                ('company_phone', models.CharField(default='+213 21 XX XX XX', max_length=20, verbose_name="Téléphone de l'entreprise")),
                ('company_email', models.EmailField(default='info@bureauauto.dz', max_length=254, verbose_name="Email de l'entreprise")),
                ('default_tva_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux TVA par défaut (%)')),
                ('default_tariff_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux tarifaire par défaut (%)')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de commission par défaut (%)')),
                ('reservation_duration_days', models.PositiveIntegerField(default=7, verbose_name='Durée de réservation (jours)')),
                ('invoice_due_days', models.PositiveIntegerField(default=30, verbose_name='Échéance facture (jours)')),
                ('enable_email_notifications', models.BooleanField(default=True, verbose_name='Activer les notifications email')),
                ('enable_overdue_alerts', models.BooleanField(default=True, verbose_name='Activer les alertes de retard')),
                ('overdue_alert_days', models.PositiveIntegerField(default=7, verbose_name='Alerte de retard après (jours)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_currency', models.ForeignKey(limit_choices_to={'code': 'DA'}, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Devise par défaut')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configurations système',
            },
        ),
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la configuration')),
                ('backup_type', models.CharField(choices=[('full', 'Sauvegarde complète'), ('incremental', 'Sauvegarde incrémentale')], default='full', max_length=20, verbose_name='Type de sauvegarde')),
                ('frequency', models.CharField(choices=[('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='daily', max_length=20, verbose_name='Fréquence')),
                ('storage_path', models.CharField(max_length=500, verbose_name='Chemin de stockage')),
                ('max_backups_to_keep', models.PositiveIntegerField(default=30, verbose_name='Nombre max de sauvegardes à conserver')),
                ('next_backup', models.DateTimeField(verbose_name='Prochaine sauvegarde')),
                ('last_backup', models.DateTimeField(blank=True, null=True, verbose_name='Dernière sauvegarde')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration de sauvegarde',
                'verbose_name_plural': 'Configurations de sauvegarde',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de change')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'effet")),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Source du taux')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history_from', to='core.currency', verbose_name='Devise source')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history_to', to='core.currency', verbose_name='Devise cible')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique des taux de change',
                'verbose_name_plural': 'Historiques des taux de change',
                'ordering': ['-effective_date'],
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
    ]
