# Generated by Django 4.2.28 on 2026-03-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='bank_rib',
            field=models.CharField(blank=True, max_length=30, verbose_name='RIB'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Recommandé : PNG transparent, max 2 Mo', null=True, upload_to='company/logo/', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_nis',
            field=models.CharField(blank=True, help_text="Numéro d'Identification Statistique", max_length=20, verbose_name='NIS'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='company_rc',
            field=models.CharField(blank=True, help_text='Registre du Commerce', max_length=30, verbose_name='Numéro RC'),
        ),
    ]
