# Generated by Django 4.2.28 on 2026-02-13 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de vente')),
                ('sale_date', models.DateField(verbose_name='Date de vente')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente (DA)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement Bancaire'), ('installment', 'Paiement Échelonné'), ('check', 'Chèque')], max_length=20, verbose_name='Mode de paiement')),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Acompte (DA)')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de commission (%)')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant commission (DA)')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Finalisée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assigned_trader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_as_trader', to=settings.AUTH_USER_MODEL, verbose_name='Trader assigné')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Client')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('invoice_date', models.DateField(verbose_name='Date de facture')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('subtotal_ht', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sous-total HT (DA)')),
                ('tva_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux TVA (%)')),
                ('tva_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant TVA (DA)')),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total TTC (DA)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant payé (DA)')),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde dû (DA)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émise'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Client')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sales.sale', verbose_name='Vente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
    ]
